-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
--@localization(locale="deDE", format="lua_table", handle-subnamespaces="subtable", handle-unlocalized="english")@
--@do-not-package@
{
	PrintOut = {
		Say = "geladen! /rc zum öffnen des Menüs",
		Description = "Es ist ein Kombinations Guid für Runen."
	},
	Menu = {
		Grade = "Grad ",
		Tier1 = "Rang ",
		Tier2 = " Runen",
		Buildable = "Baubare Runen",
		Needed = "Benötigte Runen",
		BuildList = "Build List"
	},
	Runes = {
		Deactive = "Deaktiviert", -- comb 5 = 2
		NoMake = "Nicht herstellbar", --comb 5 = 3
		TreasureHunt = "In Minispiel findbar", --comb 5 = 4
		AltMake = "alternatives Rezept", -- comb 5 = 6
		ShortAlt = "alt." -- not working now, text is directly in runes database
	}
}
--@end-do-not-package@