-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
--@localization(locale="enUS", format="lua_table", handle-subnamespaces="subtable", handle-unlocalized="english")@
--@do-not-package@
{
	PrintOut = {
		Say = "loaded! /rc to open RuneCraft",
		Description = "Its a combination Guide for Runes."
	},
	Menu = {
		Grade = "Grade ",
		Tier1 = "Rank ",
		Tier2 = " Runes",
		Buildable = "Buildable Runes",
		Needed = "Needed Runes",
		BuildList = "Build List"
	},
	Runes = {
		Deactive = "Deactivated", -- comb 5 = 2
		NoMake = "Not produceable", --comb 5 = 3
		TreasureHunt = "From mini-games", --comb 5 = 4
		AltMake = "Alternative recipe", -- comb 5 = 6
		ShortAlt = "alt." -- not working now, text is directly in runes database
	}
}
--@end-do-not-package@