-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
--@localization(locale="esES", format="lua_table", handle-subnamespaces="subtable", handle-unlocalized="english")@
--@do-not-package@
{
	PrintOut = {
		Say = "Cargado! /rc para abrir RuneCraft",
		Description = "Es una Guía de combinación de Runas."
	},
	Menu = {
		Grade = "Grado ",
		Tier1 = "Rango ",
		Tier2 = " Runas",
		Buildable = "Runas realizables",
		Needed = "Runas necesarias",
		BuildList = "Build List"
	},
	Runes = {
		Deactive = "Desactivado", -- comb 5 = 2
		NoMake = "No realizable", --comb 5 = 3
		TreasureHunt = "De minijuegos", --comb 5 = 4
		AltMake = "Receta alternativa", -- comb 5 = 6
		ShortAlt = "alt." -- not working now, text is directly in runes database
	}
}
--@end-do-not-package@