-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
--@localization(locale="frFR", format="lua_table", handle-subnamespaces="subtable", handle-unlocalized="english")@
--@do-not-package@
{
	PrintOut = {
		Say = "chargé! /rc pour ouvrir RuneCraft",
		Description = "Guide des combinaisons de Runes."
	},
	Menu = {
		Grade = "Rang ",
		Tier1 = "Catégorie ",
		Tier2 = " Runes",
		Buildable = "Runes Craftables",
		Needed = "Runes nécessaires",
		BuildList = "Build List"
	},
	Runes = {
		Deactive = "Désactivée", -- comb 5 = 2
		NoMake = "Non-craftabe", --comb 5 = 3
		TreasureHunt = "Provient des mini-jeux", --comb 5 = 4
		AltMake = "Recette Alternative", -- comb 5 = 6
		ShortAlt = "alt." -- not working now, text is directly in runes database
	}
}
--@end-do-not-package@