-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
--@localization(locale="koKR", format="lua_table", handle-subnamespaces="subtable", handle-unlocalized="english")@
--@do-not-package@
{
	PrintOut = {
		Say = "로드되었습니다.",
		Description = "룬 조합 가이드입니다."
	},
	Menu = {
		Grade = "메뉴 ",
		Tier1 = "랭크 ",
		Tier2 = " 룬",
		Buildable = "제작가능 룬",
		Needed = "필요한 룬",
		BuildList = "Build List"
	},
	Runes = {
		Deactive = "비활성화 됨", -- comb 5 = 2
		NoMake = "생산 된 할 수 없습니다", --comb 5 = 3
		TreasureHunt = "미니 가지 게임에서", --comb 5 = 4
		AltMake = "Alternative recipe", -- comb 5 = 6
		ShortAlt = "alt." -- not working now, text is directly in runes database
	}
}
--@end-do-not-package@