-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
--@localization(locale="plPL", format="lua_table", handle-subnamespaces="subtable", handle-unlocalized="english")@
--@do-not-package@
{
	PrintOut = {
		Say = "załadowany! Wpisz /rc, aby otworzyć RuneCraft",
		Description = "Poradnik do tworzenia run."
	},
	Menu = {
		Grade = "Stopień ",
		Tier = "Runy rangi <TIER>",
		UnrankedTier = "Runy bez rangi",
		Buildable = "Możliwe do stworzenia",
		Needed = "Potrzebne runy",
		BuildList = "Lista tworzenia"
	},
	Runes = {
		Deactive = "Wyłączona", -- comb 5 = 2
		NoMake = "Niewykonywalna", --comb 5 = 3
		TreasureHunt = "Z minigierek", --comb 5 = 4
		AltMake = "Inny sposób wytworzenia", -- comb 5 = 6
		ShortAlt = "alt." -- not working now, text is directly in runes database
	}
}
--@end-do-not-package@