-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
--@localization(locale="ruRU", format="lua_table", handle-subnamespaces="subtable", handle-unlocalized="english")@
--@do-not-package@
{
	PrintOut = {
		Say = "загружен! /rc для открытия RuneCraft",
		Description = "Справочник по комбинациям рун."
	},
	Menu = {
		Grade = "Уровень ",
		Tier1 = "Ранг ",
		Tier2 = " Руны",
		Buildable = "Создаваемые",
		Needed = "Требуемые",
		BuildList = "Build List"
	},
	Runes = {
		Deactive = "Отключенные", -- comb 5 = 2
		NoMake = "Не крафтятся.", --comb 5 = 3
		TreasureHunt = "Руны из малатин.", --comb 5 = 4
		AltMake = "Альтернативный рецепт", -- comb 5 = 6
		ShortAlt = "альт." -- not working now, text is directly in runes database
	}
}
--@end-do-not-package@