-- coding: utf-8
--[[
-- PLEASE DO "NOT" EDIT THIS FILE!
-- This file is generated by script.
--
-- If you want to apply corrections visit:
-- http://rom.curseforge.com/addons/runecraft/localization/
--]]

return
--@localization(locale="zhTW", format="lua_table", handle-subnamespaces="subtable", handle-unlocalized="english")@
--@do-not-package@
{
	PrintOut = {
		Say = "請輸入 /rc 打開工具",
		Description = "這是一個符文組合公式工具."
	},
	Menu = {
		Grade = "等級 ",
		Tier1 = "階層 ",
		Tier2 = " 符文",
		Buildable = "符文組合",
		Needed = "所需要的符文",
		BuildList = "Build List"
	},
	Runes = {
		Deactive = "未開放合成", -- comb 5 = 2
		NoMake = "未開放", --comb 5 = 3
		TreasureHunt = "舊版資料", --comb 5 = 4
		AltMake = "特殊合成公式", -- comb 5 = 6
		ShortAlt = "特" -- not working now, text is directly in runes database
	}
}
--@end-do-not-package@